Repository DUT-Info-Montreuil/SAE-5.A-carmate-back, pull requests merged in 2023-11, with the labels that each got.

#4 chore(app): add main API file
  src/main.py
Labels: miscellaneous

#3 docs(readme, howto, development, codestyle): initialisation
  README.md
  docs/CODESTYLE.md
  docs/DEVELOPMENT.md
  docs/HOWTO.md
Labels: documentation

#8 feat(login): login mechanism - UC-34
  src/api/__init__.py
  src/api/controller/user/auth.py
  src/api/worker/auth/models/credential_dto.py
  src/api/worker/auth/use_case/login.py
  src/api/worker/user/exceptions.py
  src/database/exceptions.py
  src/database/repositories/user_repository.py
  test/auth/test_login.py
  test/mock/user/in_memory_user_repository.py
Labels: enhancement

#10 docs(development): how to launch the API via command line
  docs/DEVELOPMENT.md
Labels: documentation

#15 feat(auth): token validity check - UC-37
  src/api/controller/user/auth.py
  src/api/worker/auth/use_case/check_token.py
  src/database/repositories/token_repository.py
  test/mock/auth/in_memory_token_repository.py
Labels: enhancement

#13 feat(docker): dockerize API
  .github/workflows/publish-docker.yml
  Dockerfile
  README.md
  src/api/controller/monitoring/__init__.py
  src/api/controller/monitoring/monitoring.py
  src/main.py
Labels: enhancement
