Repository DUT-Info-Montreuil/SAE-5.A-carmate-back, pull requests merged in 2023-12, with the labels that each got.

#20 feat(docker): dockerize API
  .github/workflows/publish-docker.yml
  Dockerfile
  README.md
Labels: enhancement

#22 feat(monitoring): add routes about API monitoring
  src/api/controller/__init__.py
  src/api/controller/monitoring/__init__.py
  src/api/controller/monitoring/monitoring.py
  src/main.py
Labels: enhancement

#26 refactor(administration): change return of validate_license_api
  postman/fixture/05_insert_licenses.sql
  src/api/controller/admin/administration.py
  src/api/worker/admin/use_case/validate_license.py
  src/database/repositories/license_repository.py
  test/admin/test_validate_license.py
  test/mock/user/in_memory_license_repository.py
Labels: enhancement

#32 feat(user): get user data's from token and from id - UC-39
  src/api/controller/user/__init__.py
  src/api/controller/user/user.py
  src/api/worker/admin/models/license_to_validate.py
  src/api/worker/user/models/user_dto.py
  src/api/worker/user/use_case/__init__.py
  src/api/worker/user/use_case/get_user.py
  src/database/repositories/token_repository.py
  src/database/repositories/user_repository.py
  src/database/schemas.py
  src/main.py
  test/admin/test_get_license_to_validate.py
  test/admin/test_get_licenses_to_validate.py
  test/mock/user/in_memory_user_repository.py
  test/user/test_user.py
Labels: enhancement

#34 feat(carpooling): add search function to find carpoolings - UC-40
  postman/docker-compose.yaml
  postman/fixture/01_insert_users.sql
  postman/fixture/06_insert_driver_profiles.sql
  postman/fixture/07_insert_carpoolings.sql
  src/api/controller/carpooling/__init__.py
  src/api/controller/carpooling/search.py
  src/api/worker/carpooling/__init__.py
  src/api/worker/carpooling/models/__init__.py
  src/api/worker/carpooling/models/carpooling_dto.py
  src/api/worker/carpooling/use_case/__init__.py
  src/api/worker/carpooling/use_case/get_route_carpoolings.py
  src/database/repositories/__init__.py
  src/database/repositories/carpooling_repository.py
  src/database/schemas.py
  src/main.py
  test/mock/__init__.py
  test/mock/carpooling/__init__.py
  test/mock/carpooling/in_memory_carpooling_repository.py
Labels: enhancement

#35 fix(cors): 401 Unauthorized
  src/api/controller/user/profiles.py
  src/database/repositories/driver_profile_repository.py
  src/database/repositories/token_repository.py
  src/database/repositories/user_repository.py
  src/main.py
  src/requirements.txt
Labels: bug

#36 docs(docker): how to launch api from windows
  README.md
Labels: documentation

#28 docs(admin): administration routes
  src/api/controller/admin/administration.py
Labels: documentation

#18 feat(carpooling): create carpooling route - UC-36
  postman/fixture/04_insert_tokens.sql
  postman/fixture/05_insert_licenses.sql
  src/api/controller/admin/administration.py
  src/api/controller/carpooling/search.py
  src/api/controller/carpooling/with_driver_check.py
  src/api/controller/user/auth.py
  src/api/controller/user/profiles.py
  src/api/controller/user/user.py
  src/api/worker/admin/use_case/get_license_by_user.py
  src/api/worker/auth/models/user_information_dto.py
  src/api/worker/auth/use_case/check_token.py
  src/api/worker/carpooling/models/carpooling_dto.py
  src/api/worker/carpooling/use_case/__init__.py
  src/api/worker/carpooling/use_case/create_carpooling.py
  src/database/exceptions.py
  src/database/repositories/__init__.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/license_repository.py
  src/database/repositories/token_repository.py
  src/database/repositories/user_repository.py
  src/database/schemas.py
  src/main.py
  test/carpooling/__init__.py
  test/carpooling/test_create_carpooling.py
  test/mock/auth/in_memory_token_repository.py
  test/mock/carpooling/in_memory_carpooling_repository.py
  test/mock/carpooling/in_memory_reserve_carpooling_repository.py
  test/mock/user/in_memory_user_repository.py
Labels: enhancement

#38 feat(carpooling): add route for booking a carpooling - UC-16
  postman/docker-compose.yaml
  src/api/controller/__init__.py
  src/api/controller/admin/administration.py
  src/api/controller/carpooling/__init__.py
  src/api/controller/carpooling/booking.py
  src/api/controller/carpooling/search.py
  src/api/controller/carpooling/with_driver_check.py
  src/api/controller/user/profiles.py
  src/api/controller/user/user.py
  src/api/exceptions.py
  src/api/worker/auth/use_case/__init__.py
  src/api/worker/auth/use_case/passenger_code.py
  src/api/worker/carpooling/models/__init__.py
  src/api/worker/carpooling/models/booking_carpooling_dto.py
  src/api/worker/carpooling/use_case/__init__.py
  src/api/worker/carpooling/use_case/booking_carpooling.py
  src/api/worker/worker.py
  src/database/repositories/__init__.py
  src/database/repositories/booking_carpooling_repository.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/reserve_carpooling_repository.py
  src/database/repositories/token_repository.py
  src/database/schemas.py
  src/main.py
  src/mocks/carpooling/__init__.py
  src/mocks/carpooling/in_memory_booking_carpooling_repository.py
  src/mocks/carpooling/in_memory_carpooling_repository.py
  test/carpooling/test_booking_carpooling.py
Labels: enhancement

#31 refactor(repositories): remove try-except blocks on `establishing_connection` function
  src/api/controller/user/profiles.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/driver_profile_repository.py
  src/database/repositories/license_repository.py
  src/database/repositories/passenger_profile_repository.py
  src/database/repositories/token_repository.py
  src/database/repositories/user_admin_repository.py
  src/database/repositories/user_banned_repository.py
  src/database/repositories/user_repository.py
Labels: improve

#40 refactor(schemas): improve `DatabaseTable` schema classes
  src/api/controller/user/profiles.py
  src/database/repositories/booking_carpooling_repository.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/driver_profile_repository.py
  src/database/repositories/license_repository.py
  src/database/repositories/passenger_profile_repository.py
  src/database/repositories/token_repository.py
  src/database/repositories/user_repository.py
  src/database/schemas.py
  src/mocks/auth/in_memory_token_repository.py
  src/mocks/user/in_memory_license_repository.py
Labels: improve
