Repository DUT-Info-Montreuil/SAE-5.A-carmate-back, pull requests merged in 2024-01, with the labels that each got.

#41 feat(review): create carpoolings reviews routes - UC-42
  src/api/controller/carpooling/__init__.py
  src/api/controller/carpooling/review.py
  src/api/exceptions.py
  src/api/worker/carpooling/models/__init__.py
  src/api/worker/carpooling/models/review_dto.py
  src/api/worker/carpooling/use_case/__init__.py
  src/api/worker/carpooling/use_case/create_review.py
  src/api/worker/worker.py
  src/database/repositories/__init__.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/review_reposiotry.py
  src/database/repositories/token_repository.py
  src/database/schemas.py
  src/main.py
  src/mocks/auth/in_memory_token_repository.py
  src/mocks/carpooling/__init__.py
  src/mocks/carpooling/in_memory_carpooling_repository.py
  src/mocks/carpooling/in_memory_review_repository.py
  test/carpooling/test_create_review.py
Labels: enhancement

#49 refactor(database): change how to declare a `TABLE_NAME` and database interfaces have now a own files
  docs/HOWTO.md
  src/database/__init__.py
  src/database/interfaces/__init__.py
  src/database/interfaces/booking_carpooling_repository_interface.py
  src/database/interfaces/carpooling_repository_interface.py
  src/database/interfaces/driver_profile_repository_interface.py
  src/database/interfaces/license_repository_interface.py
  src/database/interfaces/passenger_profile_repository_interface.py
  src/database/interfaces/review_repository_interface.py
  src/database/interfaces/token_repository_interface.py
  src/database/interfaces/user_admin_repository_interface.py
  src/database/interfaces/user_banned_repository_interface.py
  src/database/interfaces/user_repository_interface.py
  src/database/repositories/__init__.py
  src/database/repositories/booking_carpooling_repository.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/driver_profile_repository.py
  src/database/repositories/license_repository.py
  src/database/repositories/passenger_profile_repository.py
  src/database/repositories/review_repository.py
  src/database/repositories/token_repository.py
  src/database/repositories/user_admin_repository.py
  src/database/repositories/user_banned_repository.py
  src/database/repositories/user_repository.py
  src/database/tables_name.py
  src/mocks/admin/in_memory_user_admin_repository.py
  src/mocks/auth/in_memory_token_repository.py
  src/mocks/carpooling/in_memory_booking_carpooling_repository.py
  src/mocks/carpooling/in_memory_carpooling_repository.py
  src/mocks/carpooling/in_memory_review_repository.py
  src/mocks/user/in_memory_driver_profile_repository.py
  src/mocks/user/in_memory_license_repository.py
  src/mocks/user/in_memory_passenger_profile_repository.py
  src/mocks/user/in_memory_user_banned_repository.py
  src/mocks/user/in_memory_user_repository.py
Labels: improve

#43 feat(scheduled-carpooling): create passenger scheduled carpooling - UC-43
  src/api/controller/admin/administration.py
  src/api/controller/carpooling/with_driver_check.py
  src/api/controller/user/__init__.py
  src/api/controller/user/schedule_carpooling.py
  src/api/exceptions.py
  src/api/worker/auth/use_case/__init__.py
  src/api/worker/auth/use_case/check_token.py
  src/api/worker/auth/use_case/passenger_code.py
  src/api/worker/carpooling/use_case/__init__.py
  src/api/worker/carpooling/use_case/booking_carpooling.py
  src/api/worker/carpooling/use_case/check_for_matching_passenger_scheduled.py
  src/api/worker/user/use_case/__init__.py
  src/api/worker/user/use_case/create_passenger_scheduled_carpooling.py
  src/api/worker/user/use_case/look_for_carpoolings.py
  src/api/worker/worker.py
  src/database/interfaces/__init__.py
  src/database/interfaces/booking_carpooling_repository_interface.py
  src/database/interfaces/propose_scheduled_carpooling_repository_interface.py
  src/database/repositories/__init__.py
  src/database/repositories/booking_carpooling_repository.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/propose_scheduled_carpooling.py
  src/database/repositories/token_repository.py
  src/database/schemas.py
  src/database/tables_name.py
  src/main.py
  src/mocks/auth/in_memory_token_repository.py
  src/mocks/carpooling/in_memory_booking_carpooling_repository.py
  src/mocks/carpooling/in_memory_carpooling_repository.py
  src/mocks/user/__init__.py
  src/mocks/user/in_memory_propose_scheduled_carpooling_repository.py
  src/services/__init__.py
  src/services/passenger_code.py
  test/carpooling/test_check_for_matching_passenger_scheduled.py
  test/user/test_create_passenger_scheduled_carpooling.py
  test/user/test_look_for_carpooling.py
Labels: enhancement

#45 refactor(profiles): add in Profiles DTO's the profile picture
  src/api/worker/user/models/driver_profile_dto.py
  src/api/worker/user/models/passenger_profile_dto.py
  src/api/worker/user/use_case/get_driver_profile.py
  src/api/worker/user/use_case/get_passenger_profile.py
  src/api/worker/worker.py
  src/database/interfaces/driver_profile_repository_interface.py
  src/database/repositories/driver_profile_repository.py
  src/database/repositories/passenger_profile_repository.py
  src/mocks/user/in_memory_driver_profile_repository.py
  src/mocks/user/in_memory_passenger_profile_repository.py
Labels: improve

#50 fix(reserve-create-conflicts): fix conflicts between reservation and creation
  src/api/controller/carpooling/booking.py
  src/api/controller/carpooling/with_driver_check.py
  src/api/exceptions.py
  src/api/worker/carpooling/use_case/booking_carpooling.py
  src/api/worker/carpooling/use_case/create_carpooling.py
  src/database/interfaces/booking_carpooling_repository_interface.py
  src/database/interfaces/carpooling_repository_interface.py
  src/database/interfaces/propose_scheduled_carpooling_repository_interface.py
  src/database/interfaces/token_repository_interface.py
  src/database/repositories/booking_carpooling_repository.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/propose_scheduled_carpooling.py
  src/mocks/carpooling/in_memory_booking_carpooling_repository.py
  src/mocks/carpooling/in_memory_carpooling_repository.py
  src/mocks/user/in_memory_propose_scheduled_carpooling_repository.py
  test/carpooling/test_booking_carpooling.py
  test/carpooling/test_create_carpooling.py
Labels: bug

#46 feat(scoreboard): add listings of best drivers accordings to criterion - UC-44
  postman/docker-compose.yaml
  postman/fixture/01_insert_users.sql
  postman/fixture/06_insert_driver_profiles.sql
  src/api/controller/__init__.py
  src/api/controller/scoreboard/__init__.py
  src/api/controller/scoreboard/scoreboard.py
  src/api/worker/scoreboard/__init__.py
  src/api/worker/scoreboard/models/__init__.py
  src/api/worker/scoreboard/models/score_dto.py
  src/api/worker/scoreboard/use_case/__init__.py
  src/api/worker/scoreboard/use_case/get_best_economic_driving_rating.py
  src/api/worker/scoreboard/use_case/get_best_safe_driving_rating.py
  src/api/worker/scoreboard/use_case/get_best_sociability_rating.py
  src/api/worker/worker.py
  src/database/interfaces/review_repository_interface.py
  src/database/repositories/review_repository.py
  src/database/schemas.py
  src/main.py
  src/mocks/auth/in_memory_token_repository.py
  src/mocks/carpooling/in_memory_review_repository.py
  src/mocks/user/in_memory_driver_profile_repository.py
  src/mocks/user/in_memory_passenger_profile_repository.py
  src/mocks/user/in_memory_user_repository.py
  test/scoreboard/__init__.py
  test/scoreboard/test_scoreboard.py
  test/user/test_passenger_profile.py
Labels: enhancement

#51 docs: refresh documentations
  README.md
  docs/CODESTYLE.md
  docs/DEVELOPMENT.md
  docs/HOWTO.md
Labels: documentation

#47 ci(naming-convention-check): add GitHub Actions for checking file and folder names
  .github/workflows/naming-convention-check.yml
  src/database/repositories/__init__.py
  src/database/repositories/propose_scheduled_carpooling_repository.py
Labels: enhancement

#44 feat(history): add users carpoolings done history routes - UC-28
  src/api/controller/user/__init__.py
  src/api/controller/user/history.py
  src/api/controller/user/published_carpooling.py
  src/api/worker/carpooling/models/carpooling_dto.py
  src/api/worker/user/models/__init__.py
  src/api/worker/user/models/booked_carpooling_dto.py
  src/api/worker/user/models/propose_scheduled_carpooling_dto.py
  src/api/worker/user/models/published_carpooling_dto.py
  src/api/worker/user/models/published_schedule_carpooling_dto.py
  src/api/worker/user/use_case/__init__.py
  src/api/worker/user/use_case/get_carpooling_booked.py
  src/api/worker/user/use_case/get_propose_scheduled_carpoolings.py
  src/api/worker/user/use_case/get_published_carpooling.py
  src/api/worker/user/use_case/get_published_schedule_carpooling.py
  src/database/__init__.py
  src/database/interfaces/booking_carpooling_repository_interface.py
  src/database/interfaces/carpooling_repository_interface.py
  src/database/interfaces/propose_scheduled_carpooling_repository_interface.py
  src/database/interfaces/scheduled_carpooling_repository_interface.py
  src/database/repositories/booking_carpooling_repository.py
  src/database/repositories/carpooling_repository.py
  src/database/repositories/propose_scheduled_carpooling_repository.py
  src/database/repositories/scheduled_carpooling_repository.py
  src/main.py
  src/mocks/carpooling/in_memory_booking_carpooling_repository.py
  src/mocks/carpooling/in_memory_carpooling_repository.py
Labels: enhancement
